FROM node:18-alpine

WORKDIR /app

RUN npm install -g json-server nodemon

EXPOSE 8080

CMD ["nodemon", "--legacy-watch", "--watch", "db.json", "--exec", "json-server", "--", "db.json", "--host", "localhost", "--port", "8080"]
